version: "3.9"

services:
  db:
    image: mongo
    container_name: db
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo-data:/data/db

  api:
    image: backend-challenge
    container_name: node_api
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  mongo-data: 
      driver: local
